language: go
go:
  - 1.11.1
  - 1.11.2
  - 1.11.3
  - 1.11.4
sudo: required
addons:
  apt:
    packages:
      - libpcap-dev
before_install:
  - sudo apt-get install libpcap-dev 
script:
  - env GO111MODULE=on go build